"""add token columns

Revision ID: 640afb1454c6
Revises: add624ae1661
Create Date: 2026-06-14 15:52:20.253374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640afb1454c6'
down_revision: Union[str, None] = 'add624ae1661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default required for SQLite — cannot ADD NOT NULL column without it
    op.add_column('dataset_queries', sa.Column('input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dataset_queries', sa.Column('output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dataset_queries', sa.Column('cost_usd', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('queries', sa.Column('input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('queries', sa.Column('output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('queries', sa.Column('cost_usd', sa.Float(), nullable=False, server_default='0.0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'cost_usd')
    op.drop_column('queries', 'output_tokens')
    op.drop_column('queries', 'input_tokens')
    op.drop_column('dataset_queries', 'cost_usd')
    op.drop_column('dataset_queries', 'output_tokens')
    op.drop_column('dataset_queries', 'input_tokens')
    # ### end Alembic commands ###
