"""add_usage_stats_to_query_records

Revision ID: daa92380e008
Revises: 1b427cf1b124
Create Date: 2026-06-16 12:54:23.086071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa92380e008'
down_revision: Union[str, None] = '1b427cf1b124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_records', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('query_records', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('query_records', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('query_records', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    op.add_column('query_records', sa.Column('api_request_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_records', 'api_request_count')
    op.drop_column('query_records', 'estimated_cost_usd')
    op.drop_column('query_records', 'total_tokens')
    op.drop_column('query_records', 'output_tokens')
    op.drop_column('query_records', 'input_tokens')
    # ### end Alembic commands ###
